window.GAME_DATA = [
  { title:'Crazy Cattle 3D', image:'img/games/crazycattle3d.png', tags:['action'], src:'games/crazycattle3d/index.html' },
  { title:'Slope', image:'img/games/slope.png', tags:['racing','action'], src:'games/slope/index.html' },
  { title:'Retro Highway', image:'img/games/retrohighway.png', tags:['racing'], src:'games/retrohighway/index.html' },
  { title:'1v1.lol', image:'img/games/1v1lol.png', tags:['shooter','action'], src:'games/1v1lol/index.html' },
  { title:'Super Star Car', image:'img/games/superstarcar.png', tags:['racing','action'], src:'games/superstarcar/index.html' },
  { title:'Block Blast', image:'img/games/blockblast.png', tags:['puzzle'], src:'games/blockblast/index.html' },
  { title:'Drift Hunters', image:'img/games/drifthunters.png', tags:['racing','action'], src:'games/drifthunters/index.html' },
  { title:'Snow Rider 3D', image:'img/games/snowrider3d.png', tags:['racing'], src:'games/snowrider3d/index.html' },
  { title:'Cookie Clicker', image:'img/games/cookieclicker.png', tags:['idle','clicker'], src:'games/cookieclicker/index.html' },
  { title:'Retrobowl', image:'img/games/retrobowl.png', tags:['sports','action'], src:'games/retrobowl/index.html' },
  { title:'Monkey Mart', image:'img/games/monkeymart.png', tags:['idle'], src:'games/monkeymart/index.html' },
  { title:'Super Mario 64', image:'img/games/supermario64.png', tags:['adventure','action'], src:'games/supermario64/index.html' },
  { title:'Eaglercraft 1.5.2', image:'img/games/eaglercraft.png', tags:['sandbox','adventure'], src:'games/eaglercraft/index.html' },
  { title:'8 Ball Pool', image:'img/games/8ballpool.png', tags:['sports'], src:'games/8ballpool/index.html' },
  { title:'Awesome Tanks 2', image:'img/games/awesometanks2.png', tags:['action','shooting'], src:'games/awesometanks2/index.html' },
  { title:'Clicker Heros', image:'img/games/clickerheros.png', tags:['idle','clicker'], src:'games/clickerheros/index.html' },
  { title:'Gun Spin', image:'img/games/gunspin.png', tags:['shooting','action'], src:'games/gunspin/index.html' },
  { title:'Basket Random', image:'img/games/basketrandom.png', tags:['sports','action'], src:'games/basketrandom/index.html' },
  { title:'Soccer Random', image:'img/games/soccerrandom.png', tags:['sports','action'], src:'games/soccerrandom/index.html' },
  { title:'Volley Random', image:'img/games/volleyrandom.png', tags:['sports','action'], src:'games/volleyrandom/index.html' },
  { title:'Boxing Random', image:'img/games/boxingrandom.png', tags:['sports','action'], src:'games/boxingrandom/index.html' },
  { title:'Grindcraft', image:'img/games/grindcraft.png', tags:['idle'], src:'games/grindcraft/index.html' },
  { title:'Golf Champions', image:'img/games/golfchampions.png', tags:['sports'], src:'games/golfchampions/index.html' },
  { title:'Fruit Merge', image:'img/games/fruitmerge.png', tags:['puzzle'], src:'games/fruitmerge/index.html' },
  { title:'Johnny Upgrade', image:'img/games/johnnyupgrade.png', tags:['action','runner'], src:'games/johnnyupgrade/index.html' },
  { title:'Duck Life 1', image:'img/games/ducklife1.png', tags:['adventure'], src:'games/ducklife1/index.html' },
  { title:'Duck Life 2', image:'img/games/ducklife2.png', tags:['adventure'], src:'games/ducklife2/index.html' },
  { title:'Duck Life 3', image:'img/games/ducklife3.png', tags:['adventure'], src:'games/ducklife3/index.html' },
  { title:'Idle Breakout', image:'img/games/idlebreakout.png', tags:['idle','clicker'], src:'games/idlebreakout/index.html' },
  { title:'Drive Mad', image:'img/games/drivemad.png', tags:['racing','adventure'], src:'games/drivemad/index.html' },
  { title:'Monster Tracks', image:'img/games/monstertracks.png', tags:['adventure'], src:'games/monstertracks/index.html' },
  { title:'Doodle Cricket', image:'img/games/doodlecricket.png', tags:['sports'], src:'games/doodlecricket/index.html' },
  { title:'Tomb Of The Mask', image:'img/games/tombofthemask.png', tags:['puzzle'], src:'games/tombofthemask/index.html' },
  { title:'3D Bowling', image:'img/games/3dbowling.png', tags:['sports'], src:'games/3dbowling/index.html' },
  { title:'Hole.io', image:'img/games/holeio.png', tags:['action'], src:'games/holeio/index.html' },
  { title:'Jetpack Joyride', image:'img/games/jetpackjoyride.png', tags:['runner'], src:'games/jetpackjoyride/index.html' }
];

window.TAGS = [
  { id:'favorites', label:'Favorites' },
  { id:'all', label:'All' },
  { id:'racing', label:'Racing' },
  { id:'action', label:'Action' },
  { id:'puzzle', label:'Puzzle' },
  { id:'idle', label:'Idle' },
  { id:'sports', label:'Sports' },
  { id:'sandbox', label:'Sandbox' },
  { id:'runner', label:'Runner' },
  { id:'clicker', label:'Clicker' },
  { id:'shooting', label:'Shooting' },
  { id:'adventure', label:'Adventure' }
];