window.GAME_DATA = [
  { title:'Crazy Cattle 3D', image:'img/games/crazycattle3d.png', tags:['action'], src:'games/crazycattle3d/index.html' },
  { title:'Slope', image:'img/games/slope.png', tags:['racing','action'], src:'games/slope/index.html' },
  { title:'Retro Highway', image:'img/games/retrohighway.png', tags:['racing'], src:'games/retrohighway/index.html' },
  { title:'1v1.lol', image:'img/games/1v1lol.png', tags:['shooter','action'], src:'games/1v1lol/index.html' },
  { title:'Super Star Car', image:'img/games/superstarcar.png', tags:['racing','action'], src:'games/superstarcar/index.html' },
  { title:'Block Blast', image:'img/games/blockblast.png', tags:['puzzle'], src:'games/blockblast/index.html' },
  { title:'Drift Hunters', image:'img/games/drifthunters.png', tags:['racing','action'], src:'games/drifthunters/index.html' },
  { title:'Snow Rider 3D', image:'img/games/snowrider3d.png', tags:['racing'], src:'games/snowrider3d/index.html' },
  { title:'Cookie Clicker', image:'img/games/cookieclicker.png', tags:['idle','clicker'], src:'games/cookieclicker/index.html' },
  { title:'Retrobowl', image:'img/games/retrobowl.png', tags:['sports','action'], src:'games/retrobowl/index.html' },
  { title:'Monkey Mart', image:'img/games/monkeymart.png', tags:['idle'], src:'games/monkeymart/index.html' },
  { title:'Super Mario 64', image:'img/games/supermario64.png', tags:['adventure','action'], src:'games/supermario64/index.html' },
  { title:'Eaglercraft 1.5.2', image:'img/games/eaglercraft.png', tags:['sandbox','adventure'], src:'games/eaglercraft/index.html' },
  { title:'8 Ball Pool', image:'img/games/8ballpool.png', tags:['sports'], src:'games/8ballpool/index.html' },
  { title:'Awesome Tanks 2', image:'img/games/awesometanks2.png', tags:['action','shooting'], src:'games/awesometanks2/index.html' },
  { title:'Clicker Heros', image:'img/games/clickerheros.png', tags:['idle','clicker'], src:'games/clickerheros/index.html' },
  { title:'Gun Spin', image:'img/games/gunspin.png', tags:['shooting','action'], src:'games/gunspin/index.html' },
  { title:'Basket Random', image:'img/games/basketrandom.png', tags:['sports','action'], src:'games/basketrandom/index.html' },
  { title:'Soccer Random', image:'img/games/soccerrandom.png', tags:['sports','action'], src:'games/soccerrandom/index.html' },
  { title:'Volley Random', image:'img/games/volleyrandom.png', tags:['sports','action'], src:'games/volleyrandom/index.html' },
  { title:'Boxing Random', image:'img/games/boxingrandom.png', tags:['sports','action'], src:'games/boxingrandom/index.html' },
  { title:'Grindcraft', image:'img/games/grindcraft.png', tags:['idle'], src:'games/grindcraft/index.html' },
  { title:'Golf Champions', image:'img/games/golfchampions.png', tags:['sports'], src:'games/golfchampions/index.html' },
  { title:'Fruit Merge', image:'img/games/fruitmerge.png', tags:['puzzle'], src:'games/fruitmerge/index.html' },
  { title:'Johnny Upgrade', image:'img/games/johnnyupgrade.png', tags:['action','runner'], src:'games/johnnyupgrade/index.html' },
  { title:'Duck Life 1', image:'img/games/ducklife1.png', tags:['adventure'], src:'games/ducklife1/index.html' },
  { title:'Duck Life 2', image:'img/games/ducklife2.png', tags:['adventure'], src:'games/ducklife2/index.html' },
  { title:'Duck Life 3', image:'img/games/ducklife3.png', tags:['adventure'], src:'games/ducklife3/index.html' },
  { title:'Idle Breakout', image:'img/games/idlebreakout.png', tags:['idle','clicker'], src:'games/idlebreakout/index.html' },
  { title:'Drive Mad', image:'img/games/drivemad.png', tags:['racing','adventure'], src:'games/drivemad/index.html' },
  { title:'Monster Tracks', image:'img/games/monstertracks.png', tags:['adventure'], src:'games/monstertracks/index.html' },
  { title:'Doodle Cricket', image:'img/games/doodlecricket.png', tags:['sports'], src:'games/doodlecricket/index.html' },
  { title:'Tomb Of The Mask', image:'img/games/tombofthemask.png', tags:['puzzle'], src:'games/tombofthemask/index.html' },
  { title:'3D Bowling', image:'img/games/3dbowling.png', tags:['sports'], src:'games/3dbowling/index.html' },
  { title:'Hole.io', image:'img/games/holeio.png', tags:['action'], src:'games/holeio/index.html' },
  { title:'Jetpack Joyride', image:'img/games/jetpackjoyride.png', tags:['runner'], src:'games/jetpackjoyride/index.html' },
  
  
  
  
  { title:'2048', image:'img/games/2048.png', tags:['puzzle'], src:'games/2048/index.html' },
  { title:'Bacon May Die', image:'img/games/baconmaydie.png', tags:['action','shooting'], src:'games/baconmaydie/index.html' },
  { title:'Baldis Basics', image:'img/games/baldisbasics.png', tags:['adventure','puzzle','action'], src:'games/baldis-basics/index.html' },
  { title:'Basketball Stars', image:'img/games/basketballstars.png', tags:['sports'], src:'games/basketball-stars/index.html' },
  { title:'Bitlife', image:'img/games/bitlife.png', tags:['idle','clicker'], src:'games/bit-life/index.html' },
  { title:'Blocky Snakes', image:'img/games/blockysnakes.png', tags:['runner','action'], src:'games/blocky-snakes/index.html' },
  { title:'Bloxorz', image:'img/games/bloxorz.png', tags:['puzzle'], src:'games/bloxorz/index.html' },
  { title:'Bottle Flip 3D', image:'img/games/bottleflip3d.png', tags:['runner','action'], src:'games/bottle-flip-3d/index.html' },
  { title:'Burrito Bison', image:'img/games/burritobison.png', tags:['action','runner'], src:'games/burrito-bison/index.html' },
  { title:'Candy Jump', image:'img/games/candyjump.png', tags:['runner','action'], src:'games/candyjump/index.html' },
  { title:'Chrome Dino', image:'img/games/chromedino.png', tags:['runner'], src:'games/chrome-dino/index.html' },
  { title:'Crazy Cars', image:'img/games/crazycars.png', tags:['racing'], src:'games/crazy-cars/index.html' },
  { title:'Crossy Road', image:'img/games/crossyroad.png', tags:['runner','action'], src:'games/crossy-road/index.html' },
  { title:'Cubes 2048', image:'img/games/cubes2048.png', tags:['puzzle','action'], src:'games/cubes-2048/index.html' },
  { title:'Dead Again', image:'img/games/deadagain.png', tags:['action','adventure'], src:'games/dead-again/index.html' },
  { title:'Death Run 3D', image:'img/games/deathrun3d.png', tags:['runner','action'], src:'games/death-run-3d/index.html' },
  { title:'Doge Miner', image:'img/games/dogeminer.png', tags:['clicker','idle'], src:'games/doge-miner/index.html' },
  { title:'Down The Hill', image:'img/games/downthehill.png', tags:['runner','action'], src:'games/downthehill/index.html' },
  { title:'Drift Boss', image:'img/games/driftboss.png', tags:['racing'], src:'games/drift-boss/index.html' },
  { title:'Earn To Die', image:'img/games/earntodie.png', tags:['racing','action','adventure'], src:'games/earn-to-die/index.html' },
  { title:'Eggy Car', image:'img/games/eggycar.png', tags:['racing','action'], src:'games/eggycar/index.html' },
  { title:'Elastic Man', image:'img/games/elasticman.png', tags:['action'], src:'games/elasticman/index.html' },
  { title:'Flappy Bird', image:'img/games/flappybird.png', tags:['runner','action'], src:'games/flappy-bird/index.html' },
  { title:'Hide And Smash', image:'img/games/hideandsmash.png', tags:['action','adventure'], src:'games/hide-and-smash/index.html' },
  { title:'Idle Ants', image:'img/games/idleants.png', tags:['idle','clicker'], src:'games/idle-ants/index.html' },
  { title:'Idle Tree City', image:'https://imgs.search.brave.com/v70lC3kpGpCuyOoVtEXnAnz8g8PnwmIMYNNgRmwyavU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9iLnRo/dW1icy5yZWRkaXRt/ZWRpYS5jb20vcmpx/T2tqcmEzNEhGM0FN/MzdZSkpEX3J2VElp/NkJkdExiSVJORi05/WXlKTS5qcGc', tags:['idle','clicker'], src:'games/idle-tree-city/index.html' },
  { title:'Jungle Tower Defense', image:'img/games/jungletowerdefense.png', tags:['action','puzzle'], src:'games/jungletowerdefense/index.html' },
  { title:'Just Fall.lol', image:'img/games/justfalllol.png', tags:['action','runner'], src:'games/just-fall-lol/index.html' },
  { title:'Leader Strike', image:'img/games/leaderstrike.png', tags:['shooting','action'], src:'games/leader-strike/index.html' },
  { title:'Learn To Fly', image:'img/games/learntofly.png', tags:['action','racing'], src:'games/learn-to-fly-1/index.html' },
  { title:'Masked Forces', image:'img/games/maskedforces.png', tags:['shooting','action'], src:'games/maskedforces/index.html' },
  { title:'Eaglercraft 1.12', image:'img/games/eaglercraft.png', tags:['sandbox','adventure','action'], src:'games/minecraft-1.12/index.html' },
  { title:'Minecraft Classic', image:'img/games/minecraftclassic.png', tags:['sandbox','adventure'], src:'games/minecraft-classic/index.html' },
  { title:'Moto X3M', image:'img/games/motox3m.png', tags:['racing','action'], src:'games/moto-x3m/index.html' },
  { title:'Moto X3M 2', image:'img/games/motox3m2.png', tags:['racing','action'], src:'games/moto-x3m-2/index.html' },
  { title:'Moto X3M Pool Party', image:'img/games/motox3mpoolparty.png', tags:['racing','action'], src:'games/moto-x3m-pool-party/index.html' },
  { title:'Moto X3M Spookyland', image:'img/games/motox3mspookyland.png', tags:['racing','action'], src:'games/moto-x3m-spookyland/index.html' },
  { title:'Moto X3M Winter', image:'img/games/motox3mwinter.png', tags:['racing','action'], src:'games/moto-x3m-winter/index.html' },
  { title:'Paper IO 2', image:'img/games/paperio2.png', tags:['action','puzzle'], src:'games/paperio2/index.html' },
  { title:'Power Badminton', image:'img/games/powerbadminton.png', tags:['sports'], src:'games/pbm/index.html' },
  { title:'Penalty Kick Online', image:'img/games/penaltykicksonline.png', tags:['sports'], src:'games/penalty-kick-online/index.html' },
  { title:'Presidents Simulator', image:'https://imgs.search.brave.com/-RgHcQIHTigWtglc-XKN4IocYrRiPHgEbcyGfpzy5y8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hNTcu/Zm94bmV3cy5jb20v/c3RhdGljLmZveG5l/d3MuY29tL2ZveG5l/d3MuY29tL2NvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzA4LzEyMDAv/Njc1L0RvbmFsZC1U/cnVtcC1JbmRpY3Rt/ZW50LUZ1bHRvbi1H/ZW9yZ2lhLU11Z3No/b3RfMDIuanBnP3Zl/PTEmdGw9MQ', tags:['idle','clicker','sandbox'], src:'games/presidentsimulator/index.html' },
  { title:'Push The Box', image:'img/games/pushthebox.png', tags:['puzzle'], src:'games/push-the-box/index.html' },
  { title:'Recoil', image:'img/games/recoil.png', tags:['shooting','action'], src:'games/recoil/index.html' },
  { title:'Retrobowl College', image:'img/games/retrobowlcollege.png', tags:['sports'], src:'games/retro-bowl-college/index.html' },
  { title:'Rooftop Snipers', image:'img/games/rooftopsnipers.png', tags:['shooting','action'], src:'games/rooftop-snipers/index.html' },
  { title:'Sausage Flip', image:'img/games/sausageflip.png', tags:['runner','action'], src:'games/sausageflip/index.html' },
  { title:'Shell Shockers', image:'img/games/shellshockers.png', tags:['shooting','action'], src:'games/shell-shockers/index.html' },
  { title:'Skillfite.io', image:'img/games/skillfiteio.png', tags:['action','adventure'], src:'games/skillfite.io/index.html' },
  { title:'Sling Drift', image:'img/games/slingdrift.png', tags:['racing','action'], src:'games/sling-drift/index.html' },
  { title:'Slope 2 Player', image:'img/games/slope2player.png', tags:['runner','racing','action'], src:'games/slope-2-player/index.html' },
  { title:'Snipershot', image:'img/games/snipershot.png', tags:['shooting','action'], src:'games/snipershot/index.html' },
  { title:'Stack', image:'img/games/stack.png', tags:['puzzle','action'], src:'games/stack/index.html' },
  { title:'Stickman Hook', image:'img/games/stickmanhook.png', tags:['runner','action'], src:'games/stickman-hook/index.html' },
  { title:'Stickman Ragdoll', image:'img/games/stickmanragdoll.png', tags:['action'], src:'games/stickmanragdoll/index.html' },
  { title:'Subway Surfers', image:'img/games/subwaysurfers.png', tags:['runner','action'], src:'games/subway-surfers/index.html' },
  { title:'Super Mario Bros', image:'img/games/supermariobros.png', tags:['adventure','runner','action'], src:'games/super-mario-bros/index.html' },
  { title:'Temple Of Boom', image:'img/games/templeofboom.png', tags:['shooting','action','adventure'], src:'games/temple-of-boom/index.html' },
  { title:'Temple Run 2', image:'img/games/templerun2.png', tags:['runner','adventure','action'], src:'games/temple-run-2/index.html' },
  { title:'The Impossible Quiz', image:'img/games/tiq1.png', tags:['puzzle'], src:'games/the-impossible-quiz/index.html' },
  { title:'The Impossible Quiz 2', image:'img/games/tiq2.png', tags:['puzzle'], src:'games/tiq2/index.html' },
  { title:'Time Shooter 3', image:'img/games/timeshooter3.png', tags:['shooting','action'], src:'games/time-shooter-3/index.html' },
  { title:'Tiny Fishing', image:'img/games/tinyfishing.png', tags:['clicker','idle'], src:'games/tiny-fishing/index.html' },
  { title:'Traffic Mania', image:'img/games/trafficmania.png', tags:['racing','action'], src:'games/trafficmania/index.html' },
  { title:'Traffic Rush', image:'img/games/trafficrush.png', tags:['racing','action'], src:'games/traffic-rush/index.html' },
  { title:'Tricks', image:'img/games/tricks.png', tags:['racing','action'], src:'games/tricks/index.html' },
  { title:'Tube Clicker', image:'img/games/tubeclicker.png', tags:['clicker','idle'], src:'games/tube-clicker/index.html' },
  { title:'Tunnel Rush', image:'img/games/tunnelrush.png', tags:['runner','racing','action'], src:'games/tunnel-rush/index.html' },
  { title:'Tunnel Rush 2', image:'img/games/tunnelrush2.png', tags:['runner','racing','action'], src:'games/tunnel-rush-2/index.html' },
  { title:'Uno 4 Colors', image:'img/games/uno4colors.png', tags:['puzzle','sports'], src:'games/uno-4-colors/index.html' },
  { title:'Wordle Plus', image:'img/games/wordleplus.png', tags:['puzzle'], src:'games/wordle-plus/index.html' },
  { title:'Zombie Derby Pixel Survival', image:'img/games/zdps.png', tags:['racing','action','shooting'], src:'games/zombie-pixel-derby-survival/index.html' }
];

window.TAGS = [
  { id:'favorites', label:'Favorites' },
  { id:'all', label:'All' },
  { id:'racing', label:'Racing' },
  { id:'action', label:'Action' },
  { id:'puzzle', label:'Puzzle' },
  { id:'idle', label:'Idle' },
  { id:'sports', label:'Sports' },
  { id:'sandbox', label:'Sandbox' },
  { id:'runner', label:'Runner' },
  { id:'clicker', label:'Clicker' },
  { id:'shooting', label:'Shooting' },
  { id:'adventure', label:'Adventure' }
];